"""third

Revision ID: 6697e025fe59
Revises: 7233eda8c3a7
Create Date: 2022-08-09 12:02:36.217168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6697e025fe59'
down_revision = '7233eda8c3a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('school', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_user_school'), 'user', ['school'], unique=False)
    op.drop_column('user', 'classes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('classes', mysql.VARCHAR(length=50), nullable=True))
    op.drop_index(op.f('ix_user_school'), table_name='user')
    op.drop_column('user', 'school')
    # ### end Alembic commands ###
