"""test

Revision ID: 870129f892e1
Revises: 7622888f3365
Create Date: 2022-08-09 17:44:32.546351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '870129f892e1'
down_revision = '7622888f3365'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
