"""fourth

Revision ID: c879b88033a1
Revises: 6697e025fe59
Create Date: 2022-08-09 13:40:52.669002

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c879b88033a1'
down_revision = '6697e025fe59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('student_list', sa.String(length=100), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_email'), 'teacher', ['email'], unique=False)
    op.create_index(op.f('ix_teacher_id'), 'teacher', ['id'], unique=False)
    op.create_index(op.f('ix_teacher_name'), 'teacher', ['name'], unique=False)
    op.create_index(op.f('ix_teacher_password'), 'teacher', ['password'], unique=False)
    op.create_index(op.f('ix_teacher_student_list'), 'teacher', ['student_list'], unique=False)
    op.drop_index('ix_user_school', table_name='user')
    op.drop_column('user', 'school')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('school', mysql.VARCHAR(length=50), nullable=True))
    op.create_index('ix_user_school', 'user', ['school'], unique=False)
    op.drop_index(op.f('ix_teacher_student_list'), table_name='teacher')
    op.drop_index(op.f('ix_teacher_password'), table_name='teacher')
    op.drop_index(op.f('ix_teacher_name'), table_name='teacher')
    op.drop_index(op.f('ix_teacher_id'), table_name='teacher')
    op.drop_index(op.f('ix_teacher_email'), table_name='teacher')
    op.drop_table('teacher')
    # ### end Alembic commands ###
