"""Class model  Lacking

Revision ID: d81469562e04
Revises: f98259581421
Create Date: 2022-08-09 13:45:49.160125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd81469562e04'
down_revision = 'f98259581421'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=50), nullable=True),
    sa.Column('student_list', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_id'), 'class', ['id'], unique=False)
    op.create_index(op.f('ix_class_name'), 'class', ['name'], unique=False)
    op.create_index(op.f('ix_class_student_list'), 'class', ['student_list'], unique=False)
    op.create_index(op.f('ix_class_subject'), 'class', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_class_subject'), table_name='class')
    op.drop_index(op.f('ix_class_student_list'), table_name='class')
    op.drop_index(op.f('ix_class_name'), table_name='class')
    op.drop_index(op.f('ix_class_id'), table_name='class')
    op.drop_table('class')
    # ### end Alembic commands ###
