"""First real migration (first database schema)

Revision ID: f98259581421
Revises: c879b88033a1
Create Date: 2022-08-09 13:43:31.193699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f98259581421'
down_revision = 'c879b88033a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_description'), 'note', ['description'], unique=False)
    op.create_index(op.f('ix_note_id'), 'note', ['id'], unique=False)
    op.create_table('parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_email'), 'parent', ['email'], unique=False)
    op.create_index(op.f('ix_parent_id'), 'parent', ['id'], unique=False)
    op.create_index(op.f('ix_parent_name'), 'parent', ['name'], unique=False)
    op.create_index(op.f('ix_parent_password'), 'parent', ['password'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parent_password'), table_name='parent')
    op.drop_index(op.f('ix_parent_name'), table_name='parent')
    op.drop_index(op.f('ix_parent_id'), table_name='parent')
    op.drop_index(op.f('ix_parent_email'), table_name='parent')
    op.drop_table('parent')
    op.drop_index(op.f('ix_note_id'), table_name='note')
    op.drop_index(op.f('ix_note_description'), table_name='note')
    op.drop_table('note')
    # ### end Alembic commands ###
