"""test

Revision ID: 0015aa5644a4
Revises: c7889b286d79
Create Date: 2022-11-28 18:24:17.616605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0015aa5644a4'
down_revision = 'c7889b286d79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
