"""test06

Revision ID: 200368a458d5
Revises: b5679db4ca3e
Create Date: 2022-11-28 23:13:54.161721

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '200368a458d5'
down_revision = 'b5679db4ca3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assigments', sa.Column('assigmentId', sa.Integer(), nullable=False))
    op.drop_index('ix_assigments_sessionId', table_name='assigments')
    op.create_index(op.f('ix_assigments_assigmentId'), 'assigments', ['assigmentId'], unique=False)
    op.drop_column('assigments', 'sessionId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assigments', sa.Column('sessionId', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_assigments_assigmentId'), table_name='assigments')
    op.create_index('ix_assigments_sessionId', 'assigments', ['sessionId'], unique=False)
    op.drop_column('assigments', 'assigmentId')
    # ### end Alembic commands ###
