"""test33

Revision ID: 6b73fcd53435
Revises: 35d7860726e3
Create Date: 2022-11-28 23:06:37.340160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b73fcd53435'
down_revision = '35d7860726e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('sessionId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('numberOfActivites', sa.Integer(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('sessionId')
    )
    op.create_index(op.f('ix_sessions_name'), 'sessions', ['name'], unique=False)
    op.create_index(op.f('ix_sessions_numberOfActivites'), 'sessions', ['numberOfActivites'], unique=False)
    op.create_index(op.f('ix_sessions_sessionId'), 'sessions', ['sessionId'], unique=False)
    op.create_index(op.f('ix_sessions_userId'), 'sessions', ['userId'], unique=False)
    op.drop_index('ix_session_name', table_name='session')
    op.drop_index('ix_session_numberOfActivites', table_name='session')
    op.drop_index('ix_session_sessionId', table_name='session')
    op.drop_index('ix_session_userId', table_name='session')
    op.drop_table('session')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('sessionId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('numberOfActivites', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('userId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('sessionId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_session_userId', 'session', ['userId'], unique=False)
    op.create_index('ix_session_sessionId', 'session', ['sessionId'], unique=False)
    op.create_index('ix_session_numberOfActivites', 'session', ['numberOfActivites'], unique=False)
    op.create_index('ix_session_name', 'session', ['name'], unique=False)
    op.drop_index(op.f('ix_sessions_userId'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_sessionId'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_numberOfActivites'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_name'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
