"""test32

Revision ID: 6dc893720060
Revises: 8c4ba7a6437a
Create Date: 2022-11-28 18:27:53.726469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dc893720060'
down_revision = '8c4ba7a6437a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('userId', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_exercises_userId'), 'exercises', ['userId'], unique=False)
    op.add_column('session', sa.Column('userId', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_session_userId'), 'session', ['userId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_userId'), table_name='session')
    op.drop_column('session', 'userId')
    op.drop_index(op.f('ix_exercises_userId'), table_name='exercises')
    op.drop_column('exercises', 'userId')
    # ### end Alembic commands ###
