"""test06

Revision ID: 799c1903b35b
Revises: 200368a458d5
Create Date: 2022-11-28 23:17:09.632140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '799c1903b35b'
down_revision = '200368a458d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
