"""test32

Revision ID: 8c4ba7a6437a
Revises: dc089054efec
Create Date: 2022-11-28 18:26:22.819633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c4ba7a6437a'
down_revision = 'dc089054efec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
