"""test0112

Revision ID: 8cd6e7e90343
Revises: bb09d439e0ef
Create Date: 2022-11-29 19:26:02.738951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd6e7e90343'
down_revision = 'bb09d439e0ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('assigmentId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('numberOfActivites', sa.Integer(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('assigmentId')
    )
    op.create_index(op.f('ix_assignments_assigmentId'), 'assignments', ['assigmentId'], unique=False)
    op.create_index(op.f('ix_assignments_name'), 'assignments', ['name'], unique=False)
    op.create_index(op.f('ix_assignments_numberOfActivites'), 'assignments', ['numberOfActivites'], unique=False)
    op.create_index(op.f('ix_assignments_userId'), 'assignments', ['userId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assignments_userId'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_numberOfActivites'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_name'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_assigmentId'), table_name='assignments')
    op.drop_table('assignments')
    # ### end Alembic commands ###
