"""test05

Revision ID: b5679db4ca3e
Revises: 6b73fcd53435
Create Date: 2022-11-28 23:13:19.299059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b5679db4ca3e'
down_revision = '6b73fcd53435'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assigments',
    sa.Column('sessionId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('numberOfActivites', sa.Integer(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('sessionId')
    )
    op.create_index(op.f('ix_assigments_name'), 'assigments', ['name'], unique=False)
    op.create_index(op.f('ix_assigments_numberOfActivites'), 'assigments', ['numberOfActivites'], unique=False)
    op.create_index(op.f('ix_assigments_sessionId'), 'assigments', ['sessionId'], unique=False)
    op.create_index(op.f('ix_assigments_userId'), 'assigments', ['userId'], unique=False)
    op.drop_index('ix_sessions_name', table_name='sessions')
    op.drop_index('ix_sessions_numberOfActivites', table_name='sessions')
    op.drop_index('ix_sessions_sessionId', table_name='sessions')
    op.drop_index('ix_sessions_userId', table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('sessionId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('numberOfActivites', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('userId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('sessionId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_sessions_userId', 'sessions', ['userId'], unique=False)
    op.create_index('ix_sessions_sessionId', 'sessions', ['sessionId'], unique=False)
    op.create_index('ix_sessions_numberOfActivites', 'sessions', ['numberOfActivites'], unique=False)
    op.create_index('ix_sessions_name', 'sessions', ['name'], unique=False)
    op.drop_index(op.f('ix_assigments_userId'), table_name='assigments')
    op.drop_index(op.f('ix_assigments_sessionId'), table_name='assigments')
    op.drop_index(op.f('ix_assigments_numberOfActivites'), table_name='assigments')
    op.drop_index(op.f('ix_assigments_name'), table_name='assigments')
    op.drop_table('assigments')
    # ### end Alembic commands ###
