"""test012

Revision ID: bb09d439e0ef
Revises: c87d84e104f3
Create Date: 2022-11-29 18:12:43.651643

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb09d439e0ef'
down_revision = 'c87d84e104f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('assigmentId', sa.Integer(), nullable=False))
    op.drop_index('ix_assignments_assignmentId', table_name='assignments')
    op.create_index(op.f('ix_assignments_assigmentId'), 'assignments', ['assigmentId'], unique=False)
    op.drop_column('assignments', 'assignmentId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('assignmentId', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_assignments_assigmentId'), table_name='assignments')
    op.create_index('ix_assignments_assignmentId', 'assignments', ['assignmentId'], unique=False)
    op.drop_column('assignments', 'assigmentId')
    # ### end Alembic commands ###
