"""test

Revision ID: c7889b286d79
Revises: f16aa4120b24
Create Date: 2022-11-28 18:14:18.398243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7889b286d79'
down_revision = 'f16aa4120b24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('exerciseId', sa.Integer(), nullable=False),
    sa.Column('sessionId', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('videoLink', sa.String(length=200), nullable=True),
    sa.Column('imageLink', sa.String(length=200), nullable=True),
    sa.Column('exerciseType', sa.String(length=200), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('difficultyLevel', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('exerciseId')
    )
    op.create_index(op.f('ix_exercises_difficultyLevel'), 'exercises', ['difficultyLevel'], unique=False)
    op.create_index(op.f('ix_exercises_duration'), 'exercises', ['duration'], unique=False)
    op.create_index(op.f('ix_exercises_exerciseId'), 'exercises', ['exerciseId'], unique=False)
    op.create_index(op.f('ix_exercises_exerciseType'), 'exercises', ['exerciseType'], unique=False)
    op.create_index(op.f('ix_exercises_imageLink'), 'exercises', ['imageLink'], unique=False)
    op.create_index(op.f('ix_exercises_name'), 'exercises', ['name'], unique=False)
    op.create_index(op.f('ix_exercises_score'), 'exercises', ['score'], unique=False)
    op.create_index(op.f('ix_exercises_sessionId'), 'exercises', ['sessionId'], unique=False)
    op.create_index(op.f('ix_exercises_sets'), 'exercises', ['sets'], unique=False)
    op.create_index(op.f('ix_exercises_videoLink'), 'exercises', ['videoLink'], unique=False)
    op.create_table('session',
    sa.Column('sessionId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('numberOfActivites', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('sessionId')
    )
    op.create_index(op.f('ix_session_name'), 'session', ['name'], unique=False)
    op.create_index(op.f('ix_session_numberOfActivites'), 'session', ['numberOfActivites'], unique=False)
    op.create_index(op.f('ix_session_sessionId'), 'session', ['sessionId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_sessionId'), table_name='session')
    op.drop_index(op.f('ix_session_numberOfActivites'), table_name='session')
    op.drop_index(op.f('ix_session_name'), table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('ix_exercises_videoLink'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_sets'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_sessionId'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_score'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_name'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_imageLink'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_exerciseType'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_exerciseId'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_duration'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_difficultyLevel'), table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
