"""test04

Revision ID: c87d84e104f3
Revises: 799c1903b35b
Create Date: 2022-11-28 23:19:58.732274

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c87d84e104f3'
down_revision = '799c1903b35b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('assignmentId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('numberOfActivites', sa.Integer(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('assignmentId')
    )
    op.create_index(op.f('ix_assignments_assignmentId'), 'assignments', ['assignmentId'], unique=False)
    op.create_index(op.f('ix_assignments_name'), 'assignments', ['name'], unique=False)
    op.create_index(op.f('ix_assignments_numberOfActivites'), 'assignments', ['numberOfActivites'], unique=False)
    op.create_index(op.f('ix_assignments_userId'), 'assignments', ['userId'], unique=False)
    op.drop_index('ix_assigments_assigmentId', table_name='assigments')
    op.drop_index('ix_assigments_name', table_name='assigments')
    op.drop_index('ix_assigments_numberOfActivites', table_name='assigments')
    op.drop_index('ix_assigments_userId', table_name='assigments')
    op.drop_table('assigments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assigments',
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('numberOfActivites', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('userId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assigmentId', mysql.INTEGER(), autoincrement=False, nullable=False),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_assigments_userId', 'assigments', ['userId'], unique=False)
    op.create_index('ix_assigments_numberOfActivites', 'assigments', ['numberOfActivites'], unique=False)
    op.create_index('ix_assigments_name', 'assigments', ['name'], unique=False)
    op.create_index('ix_assigments_assigmentId', 'assigments', ['assigmentId'], unique=False)
    op.drop_index(op.f('ix_assignments_userId'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_numberOfActivites'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_name'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_assignmentId'), table_name='assignments')
    op.drop_table('assignments')
    # ### end Alembic commands ###
